[[cells]]
name = "hash-lock"
enable_type_id = false

  [cells.location]
  file = "/home/hiepthach/04_CKB/week5/simple_lock_project/ckb-rust-script/build/release/hash-lock"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x9665e6bc1966ec2bfcca4f11782d2b906f38438f"
hash_type = "type"
